config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'difficult_levels/index'
  get 'difficult_levels', to: 'difficult_levels#index', as: 'difficult_levels' # difficult level index
  get 'difficult_levels/:id', to: 'difficult_levels#show', as: 'difficult_level' # difficult level show 
  get 'difficult_levels2/:id', to: 'difficult_levels#show2', as: 'difficult_level2' # difficult level show 2 
  get 'difficult_levels3/:id', to: 'difficult_levels#show3', as: 'difficult_level3' # difficult level show 3
  get 'difficult_levels4/:id', to: 'difficult_levels#show4', as: 'difficult_level4' # difficult level show 4
  get 'difficult_levels5/:id', to: 'difficult_levels#show5', as: 'difficult_level5' # difficult level show 5
  get 'difficult_levels6/:id', to: 'difficult_levels#show6', as: 'difficult_level6' # difficult level show 6
  get 'difficult_levels7/:id', to: 'difficult_levels#show7', as: 'difficult_level7' # difficult level show 7
  get 'difficult_levels8/:id', to: 'difficult_levels#show8', as: 'difficult_level8' # difficult level show 8
  get 'difficult_levels9/:id', to: 'difficult_levels#show9', as: 'difficult_level9' # difficult level show 9
  get 'difficult_levels10/:id', to: 'difficult_levels#show10', as: 'difficult_level10' # difficult level show 10
  get 'difficult_levels11/:id', to: 'difficult_levels#show11', as: 'difficult_level11' # difficult level show 11
  get 'difficult_levels12/:id', to: 'difficult_levels#show12', as: 'difficult_level12' # difficult level show 12
  get 'difficult_levels13/:id', to: 'difficult_levels#show13', as: 'difficult_level13' # difficult level show 13
  get 'difficult_levels14/:id', to: 'difficult_levels#show14', as: 'difficult_level14' # difficult level show 14
  get 'difficult_levels15/:id', to: 'difficult_levels#show15', as: 'difficult_level15' # difficult level show 15
  get 'difficult_levels16/:id', to: 'difficult_levels#show16', as: 'difficult_level16' # difficult level show 16
  get 'difficult_levels17/:id', to: 'difficult_levels#show17', as: 'difficult_level17' # difficult level show 17
  get 'difficult_levels18/:id', to: 'difficult_levels#show18', as: 'difficult_level18' # difficult level show 18
  get 'difficult_levels19/:id', to: 'difficult_levels#show19', as: 'difficult_level19' # difficult level show 19
  get 'difficult_levels20/:id', to: 'difficult_levels#show20', as: 'difficult_level20' # difficult level show 20
  get 'difficult_levels21/:id', to: 'difficult_levels#show21', as: 'difficult_level21' # difficult level show 21
  get 'difficult_levels22/:id', to: 'difficult_levels#show22', as: 'difficult_level22' # difficult level show 22
  get 'difficult_levels23/:id', to: 'difficult_levels#show23', as: 'difficult_level23' # difficult level show 23
  get 'difficult_levels24/:id', to: 'difficult_levels#show24', as: 'difficult_level24' # difficult level show 24
  get 'difficult_levels25/:id', to: 'difficult_levels#show25', as: 'difficult_level25' # difficult level show 25
  get 'difficult_levels26/:id', to: 'difficult_levels#show26', as: 'difficult_level26' # difficult level show 26
  get 'difficult_levels27/:id', to: 'difficult_levels#show27', as: 'difficult_level27' # difficult level show 27
  get 'difficult_levels28/:id', to: 'difficult_levels#show28', as: 'difficult_level28' # difficult level show 28
  get 'difficult_levels29/:id', to: 'difficult_levels#show29', as: 'difficult_level29' # difficult level show 29
  get 'difficult_levels30/:id', to: 'difficult_levels#show30', as: 'difficult_level30' # difficult level show 30
  get 'difficult_levels31/:id', to: 'difficult_levels#show31', as: 'difficult_level31' # difficult level show 31
  get 'difficult_levels32/:id', to: 'difficult_levels#show32', as: 'difficult_level32' # difficult level show 32
  get 'difficult_levels33/:id', to: 'difficult_levels#show33', as: 'difficult_level33' # difficult level show 33
  get 'difficult_levels34/:id', to: 'difficult_levels#show34', as: 'difficult_level34' # difficult level show 34
  get 'difficult_levels35/:id', to: 'difficult_levels#show35', as: 'difficult_level35' # difficult level show 35
  get 'difficult_levels36/:id', to: 'difficult_levels#show36', as: 'difficult_level36' # difficult level show 36
  get 'difficult_levels37/:id', to: 'difficult_levels#show37', as: 'difficult_level37' # difficult level show 37
  get 'difficult_levels38/:id', to: 'difficult_levels#show38', as: 'difficult_level38' # difficult level show 38
  get 'difficult_levels39/:id', to: 'difficult_levels#show39', as: 'difficult_level39' # difficult level show 39
  get 'difficult_levels40/:id', to: 'difficult_levels#show40', as: 'difficult_level40' # difficult level show 40
  get 'difficult_levels41/:id', to: 'difficult_levels#show41', as: 'difficult_level41' # difficult level show 41
  get 'difficult_levels42/:id', to: 'difficult_levels#show42', as: 'difficult_level42' # difficult level show 42
  get 'difficult_levels43/:id', to: 'difficult_levels#show43', as: 'difficult_level43' # difficult level show 43
  get 'difficult_levels44/:id', to: 'difficult_levels#show44', as: 'difficult_level44' # difficult level show 44
  get 'difficult_levels45/:id', to: 'difficult_levels#show45', as: 'difficult_level45' # difficult level show 45
  get 'difficult_levels46/:id', to: 'difficult_levels#show46', as: 'difficult_level46' # difficult level show 46
  
  get 'challenge_levels', to: 'challenge_levels#index', as: 'challenge_levels' # challenge level index
  get 'challenge_levels/:id', to: 'challenge_levels#show', as: 'challenge_level' # challenge level show
  get 'challenge_levels2/:id', to: 'challenge_levels#show2', as: 'challenge_level2' # challenge level show page 2
  get 'challenge_levels3/:id', to: 'challenge_levels#show3', as: 'challenge_level3' # challenge level show page 3
  get 'challenge_levels4/:id', to: 'challenge_levels#show4', as: 'challenge_level4' # challenge level show page 4
  get 'challenge_levels5/:id', to: 'challenge_levels#show5', as: 'challenge_level5' # challenge level show page 5
  get 'challenge_levels6/:id', to: 'challenge_levels#show6', as: 'challenge_level6' # challenge level show page 6
  get 'challenge_levels7/:id', to: 'challenge_levels#show7', as: 'challenge_level7' # challenge level show page 7
  get 'challenge_levels8/:id', to: 'challenge_levels#show8', as: 'challenge_level8' # challenge level show page 8
  get 'challenge_levels9/:id', to: 'challenge_levels#show9', as: 'challenge_level9' # challenge level show page 9
  get 'challenge_levels10/:id', to: 'challenge_levels#show10', as: 'challenge_level10' # challenge level show page 10
  get 'challenge_levels11/:id', to: 'challenge_levels#show11', as: 'challenge_level11' # challenge level show page 11
  get 'challenge_levels12/:id', to: 'challenge_levels#show12', as: 'challenge_level12' # challenge level show page 12
  get 'challenge_levels13/:id', to: 'challenge_levels#show13', as: 'challenge_level13' # challenge level show page 13
  get 'challenge_levels14/:id', to: 'challenge_levels#show14', as: 'challenge_level14' # challenge level show page 14
  get 'challenge_levels15/:id', to: 'challenge_levels#show15', as: 'challenge_level15' # challenge level show page 15
  get 'challenge_levels16/:id', to: 'challenge_levels#show16', as: 'challenge_level16' # challenge level show page 16
  get 'challenge_levels17/:id', to: 'challenge_levels#show17', as: 'challenge_level17' # challenge level show page 17
  get 'challenge_levels18/:id', to: 'challenge_levels#show18', as: 'challenge_level18' # challenge level show page 18
  get 'challenge_levels19/:id', to: 'challenge_levels#show19', as: 'challenge_level19' # challenge level show page 19
  get 'challenge_levels20/:id', to: 'challenge_levels#show20', as: 'challenge_level20' # challenge level show page 20
  get 'challenge_levels21/:id', to: 'challenge_levels#show21', as: 'challenge_level21' # challenge level show page 21
  get 'challenge_levels22/:id', to: 'challenge_levels#show22', as: 'challenge_level22' # challenge level show page 22
  get 'challenge_levels23/:id', to: 'challenge_levels#show23', as: 'challenge_level23' # challenge level show page 23
  get 'challenge_levels24/:id', to: 'challenge_levels#show24', as: 'challenge_level24' # challenge level show page 24
  get 'challenge_levels25/:id', to: 'challenge_levels#show25', as: 'challenge_level25' # challenge level show page 25
  get 'challenge_levels26/:id', to: 'challenge_levels#show26', as: 'challenge_level26' # challenge level show page 26
  get 'challenge_levels27/:id', to: 'challenge_levels#show27', as: 'challenge_level27' # challenge level show page 27
  get 'challenge_levels28/:id', to: 'challenge_levels#show28', as: 'challenge_level28' # challenge level show page 28
  get 'challenge_levels29/:id', to: 'challenge_levels#show29', as: 'challenge_level29' # challenge level show page 29
  get 'challenge_levels30/:id', to: 'challenge_levels#show30', as: 'challenge_level30' # challenge level show page 30
  get 'challenge_levels31/:id', to: 'challenge_levels#show31', as: 'challenge_level31' # challenge level show page 31
  get 'challenge_levels32/:id', to: 'challenge_levels#show32', as: 'challenge_level32' # challenge level show page 32
  get 'challenge_levels33/:id', to: 'challenge_levels#show33', as: 'challenge_level33' # challenge level show page 33
  get 'challenge_levels34/:id', to: 'challenge_levels#show34', as: 'challenge_level34' # challenge level show page 34
  get 'challenge_levels35/:id', to: 'challenge_levels#show35', as: 'challenge_level35' # challenge level show page 35
  get 'challenge_levels36/:id', to: 'challenge_levels#show36', as: 'challenge_level36' # challenge level show page 36
  get 'challenge_levels37/:id', to: 'challenge_levels#show37', as: 'challenge_level37' # challenge level show page 37
  get 'challenge_levels38/:id', to: 'challenge_levels#show38', as: 'challenge_level38' # challenge level show page 38

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  # authenticate user - make sure the user is signed in, otherwise they cannot see see the page
  before_action :authenticate_user!, except: [:home, :about]

  # controller action for the easy, intermediate, difficult, and challenge level endpages views 
  def endpage
        respond_to do |format|
          format.html { render :endpage }
      end
    end
  # controller action for the start page view
  def start
    respond_to do |format|
      format.html { render :start }
    end
  end
  # controller action for the home page view
  def home
    respond_to do |format|
    format.html { render :home }
  end
 end
  # controller action for the about page view
  def about
    respond_to do |format|
    format.html { render :about }
   end
 end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="container-fluid" style="padding: 100px"> <!-padding for the UI->
  <div class="text-center"> <!-center text in columns for the UI->
    <div class="row">
      <div class="col-">
      <div class="text-left"> <!-move image to the left side of this column for the UI->
       <%= image_tag "boy picking apple.png", width: 400,height: 500 %> <!-image->
        </div>
        </div>
  
<div class="col">
  <div class="jumbotron"> <!- Jumbotron effect the UI->
    <div class="container-fluid">
      <h2 class="display-4">Quest for Code</h2>
      <hr class="my-4"> 
      <!- description of the motivation behind the Quest for Code game ->
       <p class="lead">Computer science students often face difficulties learning the  concepts of algorithms, 
          especially recursive algorithms. Sometimes, traditional learning methods are not effective in helping 
          students fully understand these vital concepts. Instead of struggling to learn by these traditional methods, 
          students may be more receptive to a more visual, interactive method of learning Computer Science concepts. 
          Our game, Quest for Code, provides an alternative way to learn about and master recursive tree traversal 
          algorithms. Recursive algorithms and tree traversal are two of the most basic, and often confusing, concepts 
          in algorithms and programming courses. Quest for Code was designed to help teach these concepts and improve 
          the learning experience.</p>   
       </div>
   </div>
</div>
     

app/views/static_pages/challenge_endpage.html.erb
<body class="game-bg"> <!-this shows the background image on each page and the class is in application.scss->


<div style="padding: 20px"> <!-padding for the UI->
  <div class="row no-gutters justify-content-md-center"> <!-centers columns with no space between them->
    <div class="col"> <!-first column->
      <div class="over-c-end swing-image-c-move-55"><%= image_tag "climber_right.png", height: 100 %> </div> <!-image for the climber, over-c-end is the position of the image, swing-image-c-move-55 is the animation the image does->
      <div class="under"><%= image_tag "challenge_level_33.png", height: 550 %></div> <!-image for the tree, under is the position of the image->
    </div>
    
<div style="padding: 120px"> <!-padding for the UI->
 <div class="col" align="center"> <!-second column->
  <h3>Challenge Level Cleared</h3> <!-tells player they've won the Challenge level->
    <div class="col "> <!-third column->
      <div class="alert alert-info" role="alert"> <!-alert for UI->
        <h4 class="alert-heading">Congratulations!</h4> <!-tells player they've won the Challenge level->
          <p>You've won!</p> <!-tells player they've won the Challenge level->
           <hr>
            <h4 class="mb-0">Inorder Traversal: 4, 7, 11, 2, 1, 5, 6, 8, 10, 3, 9</h4> <!-tells player the order of the nodes->
           </div>
         <div class="float-container" style="padding: 10px"> <!- puts buttons into a container ->
            <div class="float-child" style="display: inline-block"> <!- display buttons inline ->
                <%= button_to "Play Again",level_path, method: :get, class: "btn btn-success btn-lg" %> <!- link to return to level view page ->
            </div>
            <div class="float-child" style="display: inline-block"> <!- display buttons inline ->
                <%= link_to 'Exit', start_path, class: "btn btn-success btn-lg" %> <!- link to return to start view page ->
            <div>
     </div>
    </div>
  </div>
</div>

app/views/static_pages/difficult_endpage.html.erb
<body class="game-bg"> <!-this shows the background image on each page and the class is in application.scss->


<div style="padding: 20px"> <!-padding for the UI->
  <div class="row no-gutters justify-content-md-center"> <!-Makes the UI center->
    <div class="col"> <!-first column->
    <div class="over-c-end swing-image-move108"><%= image_tag "climber_right.png", height: 100 %> </div> <!-image for the climber, over-c-end is the position of the image, swing-image-move108 is the animation the image does->
      <div class="under"><%= image_tag "End_difficult.png", height: 550%></div> <!-image for the tree, under is the position of the image->
    </div>
    
<div style="padding: 150px"> <!-padding for the UI->
 <div class="col " align="center"> <!-second column->
  <h3>Difficult Level Cleared</h3> <!-tells player they've won the Difficult level->
    <div class="col ">  <!-third column->
      <div class="alert alert-info" role="alert"> <!-alert for UI->
        <h4 class="alert-heading">Congratulations!</h4> <!-tells player they've won the Difficult level->
          <p>You've won!</p> <!-tells player they've won the Difficult level->
           <hr>
            <h4 class="mb-0">Inorder Traversal: 7, 3, 2, 5, 1, 8, 4, 9, 6</h4> <!-tells player the order of the nodes->
           </div>
         <div class="float-container" style="padding: 10px"> <!- puts buttons into a container ->
            <div class="float-child" style="display: inline-block"> <!- display buttons inline ->
                <%= button_to "Play Again",level_path, method: :get, class: "btn btn-success btn-lg" %> <!- link to return to level view page ->
            </div>
            <div class="float-child" style="display: inline-block"> <!- display buttons inline ->
                <%= link_to 'Exit', start_path, class: "btn btn-success btn-lg" %> <!- link to return to start view page ->
            <div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/endpage.html.erb
<body class="game-bg"><!-this shows the background image on each page and the class is in application.scss->


<div style="padding: 20px"><!-padding for the UI->
  <div class="row no-gutters justify-content-md-center"><!-Makes the UI center->
    <div class="col">
      <div class="over-end swing-image-fifteenth-move"><%= image_tag "climber_right.png", height: 100 %> </div><!-over is the position of the climber, the swing-image is animation for moving the climber, and fall is the animation if you misclick. climber_right is the image->
      <div class="under"><%= image_tag "game_tree10.png", height: 550 %></div><!-image for game tree and under is the position of the tree->
    </div>
    
<div style="padding: 200px"><!-padding for the UI->
 <div class="col-md-auto" align="center"><!-Makes the UI center->
  <h3>Easy Level Cleared</h3>
    <div class="col ">
      <div class="alert alert-info" role="alert"><!-tells you won with an alert>
        <h4 class="alert-heading">Congratulations!</h4>
          <p>You've won!</p>
           <hr>
            <h4 class="mb-0">Inorder Traversal: 2, 1, 3</h4><!-tells you the order>
           </div>
         <div class="float-container" style="padding: 10px">
            <div class="float-child" style="display: inline-block">
                <%= button_to "Play Again",level_path, method: :get, class: "btn btn-success btn-lg" %><!-link to the level page>
            </div>
            <div class="float-child" style="display: inline-block">
                <%= link_to 'Exit', start_path, class: "btn btn-success btn-lg" %><!-button to go to start page->
            <div>
      </div>
     </div>
    </div>
  </div>
    
    

app/views/static_pages/home.html.erb
<div class="container" style="padding: 100px"> <!-padding for the UI->
  <div class="text-center"> <!-center text in the columns for the UI->
    <div class="row">
      <div class="col"> <!- first column ->
      <div class="text-left"> <!-move image to the left side of this column for the UI->
       <%= image_tag "boy picking apple.png", width: 400,height: 500 %> <!-image->
        </div>
        </div>
  
      <div class="col"> <!- second column ->
       <!-link to the devise/sessions new view for the user to sign in ->
       <h1><%= button_to "SIGN IN",new_user_session_path, method: :get, class: "btn btn-success btn-lg" %></h1>
       <!-link to the devise/registrations new view for the user register an account ->
       <h1><%= button_to "REGISTER",new_user_registration_path, method: :get, class: "btn btn-success btn-lg" %></h1>
        </div>
      </div>
  </div>

app/views/static_pages/intermediate_endpage.html.erb
<body class="game-bg"><!-this shows the background image on each page and the class is in application.scss->


<div style="padding: 20px"><!-padding for the UI->
  <div class="row no-gutters justify-content-md-center"><!-Makes the UI center->
    <div class="col">
      <div class="overend swing-image-int10"><%= image_tag "climber_right.png", height: 100 %> </div><!-over is the position of the climber, the swing-image is animation for moving the climber, and fall is the animation if you misclick. climber_right is the image->
      <div class="under"><%= image_tag "branch7.png", height: 550 %></div><!-image for game tree and under is the position of the tree->
    </div>
    
<div style="padding: 160px"><!-padding for the UI->
 <div class="col" align="center"><!-Makes the UI center->
  <h3>Intermediate Level Cleared</h3>
    <div class="col ">
      <div class="alert alert-info" role="alert"><!-tells you won with an alert>
        <h4 class="alert-heading">Congratulations!</h4>
          <p>You've won!</p>
           <hr>
            <h4 class="mb-0">Inorder Traversal: 4, 2, 5, 1, 3, 6</h4><!-tells you the order>
           </div>
         <div class="float-container" style="padding: 10px">
            <div class="float-child" style="display: inline-block">
                <%= button_to "Play Again",level_path, method: :get, class: "btn btn-success btn-lg" %><!-link to the level page>
            </div>
            <div class="float-child" style="display: inline-block">
                <%= link_to 'Exit', start_path, class: "btn btn-success btn-lg" %><!-button to go to start page->
            <div>
      </div>
     </div>
    </div>
  </div>
    
    

app/views/static_pages/start.html.erb
<div class="container" style="padding: 100px"> <!-padding for the UI->
    <div class="row">
      <div class="col"> <!- first column ->
        <div>
        <%= image_tag "boy picking apple.png", width: 400,height: 500 %> <!- image->
        </div>
      </div>
  
      <div class="col"> <!- second column ->
       <!- link to go to the first instuction view page->
       <h1 class="text-center"><%= button_to "START GAME",instruction_path, method: :get, class: "btn btn-success btn-lg" %></h1>
       <!- link for the setting options -- this just returns to the start view page becasue we were unable to enable functionality for the options->
       <h1 class="text-center"><%= button_to "OPTIONS",start_path, method: :get, class: "btn btn-success btn-lg" %></h1>
       <!- link to return to the start view page->
       <h1 class="text-center"><%= button_to "EXIT",start_path, method: :get, class: "btn btn-success btn-lg" %></h1>
      </div>
    </div>
</div>